namespace Flow;

/// <summary>
///  Defines a stream behavior that can be executed as part of a stream request handling pipeline. 
/// </summary>
/// <typeparam name="TRequest">The request witch inherits from <see cref="IStreamRequest{TResponse}"/></typeparam>
/// <typeparam name="TResponse">The result type which the request handler resturn</typeparam>
public interface IStreamPipelineBehavior<TRequest, TResponse>
    where TRequest : IStreamRequest<TResponse>
{
    /// <summary>
    /// Processes the specified request and returns a stream of responses asynchronously.
    /// </summary>
    /// <remarks>This method is typically used in middleware or pipeline scenarios where multiple handlers may
    /// process the request in sequence. The returned stream may yield zero or more responses depending on the request
    /// and handler logic.</remarks>
    /// <param name="request">The request message to be handled. Cannot be null.</param>
    /// <param name="next">A delegate that invokes the next handler in the stream processing pipeline. Used to continue the request
    /// handling sequence.</param>
    /// <param name="cancellationToken">A token that can be used to cancel the asynchronous operation.</param>
    /// <returns>An asynchronous stream of response messages generated by handling the request.</returns>
    IAsyncEnumerable<TResponse> Handle(
        TRequest request,
        StreamHandlerDelegate<TResponse> next,
        CancellationToken cancellationToken);
}
